name: GitHub Metrics
on:
  schedule: [{cron: "0 0 * * 0"}]
  workflow_dispatch:
jobs:
  # Credits: https://github.com/lowlighter/metrics
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Skyline
        uses: lowlighter/metrics@latest
        with:
          plugin_skyline: yes
          plugin_skyline_year: 2022    
          plugin_skyline_frames: 60       
          plugin_skyline_quality: 1
          plugin_skyline_compatibility: yes
          filename: assets/metrics.plugin.skyline.svg
          token: ${{ secrets.GH_NOICE }}
      - name: GitHub City
        uses: lowlighter/metrics@latest
        with:
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: 2022
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1
          plugin_skyline_settings: |
            {
              "url": "https://honzaap.github.io/GithubCity?name=${login}&year=${year}",
              "ready": "[...document.querySelectorAll('.display-info span')].map(span => span.innerText).includes('${login}')",
              "wait": 4,
              "hide": ".github-corner, .footer-link, .buttons-options, .mobile-rotate, .display-info span:first-child"
            }
          filename: assets/metrics.plugin.skyline.city.svg
          token: ${{ secrets.GH_NOICE }}
      - name: Contribution Graph
        uses: lowlighter/metrics@latest
        with:
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0
          filename: assets/github-contrib-stats.svg
          token: ${{ secrets.GH_NOICE }}
      - name: Profile Stats
        uses: lowlighter/metrics@latest
        with:
          user: nishkarshraj
          base: header
          plugin_introduction: yes
          filename: assets/github-user-stats.svg
          token: ${{ secrets.GH_NOICE }}
      - name: Recently Starred
        uses: lowlighter/metrics@latest
        with:
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 3
          filename: assets/metrics.plugin.stars.svg
          token: ${{ secrets.GH_NOICE }}

