name: GitHub Metrics
on:
  schedule: [{cron: "0 0 * * 0"}]
  workflow_dispatch:
jobs:
  # Credits: https://github.com/lowlighter/metrics
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        name: Skyline
        with:
          plugin_skyline: yes
          plugin_skyline_year: 2022    
          plugin_skyline_frames: 60       
          plugin_skyline_quality: 1
          plugin_skyline_compatibility: yes
          token: ${{ secrets.GH_NOICE }}
      - name: Contribution Graph
        uses: lowlighter/metrics@latest
        with:
          filename: github-contrib-stats.svg
          token: ${{ secrets.GH_NOICE }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0
      - name: Profile Stats
        uses: lowlighter/metrics@latest
        with:
          filename: github-user-stats.svg
          token: ${{ secrets.GH_NOICE }}
          user: nishkarshraj
          base: header
          plugin_introduction: yes


