name: Metrics
on:
  schedule: [{cron: "0 0 * * sun"}] # Runs weekly every Sunday 00:00
  push:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # Metrics.svg
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.GH_TOKEN }}
      
      # GitHub Skyline 2021
      - uses: lowlighter/metrics@latest
        with:
          plugin_skyline: yes
          plugin_skyline_year: 0           
          plugin_skyline_frames: 60       
          plugin_skyline_quality: 0.5     
          plugin_skyline_compatibility: yes # Supports Firefox and Safari
          token: ${{ secrets.GH_TOKEN }}
