name: Metrics
on:
  schedule: [{cron: "0 0 * * sun"}] # Runs weekly every Sunday 00:00
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.GH_TOKEN }}

      - uses: lowlighter/metrics@latest
        with:
          plugin_skyline: yes
          plugin_skyline_year: 0           
          plugin_skyline_frames: 60       
          plugin_skyline_quality: 0.5     
          plugin_skyline_compatibility: yes # Supports Firefox and Safari
