name: Skyline
on:
  push:
    branches: [ master ]

  workflow_dispatch:
jobs:
  skyline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: lowlighter/metrics@latest
        with:
          plugin_skyline: yes
          plugin_skyline_year: 0           
          plugin_skyline_frames: 60       
          plugin_skyline_quality: 0.5     
          plugin_skyline_compatibility: yes # Supports Firefox and Safari
