name: Metrics
on:
  schedule: [{cron: "0 0 * * sun"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        name: Skyline
        with:
          plugin_skyline: yes
          plugin_skyline_year: 2022    
          plugin_skyline_frames: 60       
          plugin_skyline_quality: 1   
          plugin_skyline_compatibility: yes
          token: ${{ secrets.GH_NOICE }}
